name: GriefDefender
main: com.griefdefender.GDBootstrap
softdepend: [dynmap, PlaceholderAPI, WorldEdit, WorldGuard, Vault]
depend: [LuckPerms]
load: STARTUP
loadafter: [EliteEnchantments]
version: '1.5.10'
api-version: 1.13
